CREATE TABLE IF NOT EXISTS music_tags (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO music_tags (name) VALUES
('rock'),
('electronic'),
('seen live'),
('alternative'),
('pop'),
('indie'),
('female vocalists'),
('metal'),
('alternative rock'),
('jazz'),
('classic rock'),
('ambient'),
('experimental'),
('folk'),
('indie rock'),
('punk'),
('Hip-Hop'),
('hard rock'),
('black metal'),
('instrumental'),
('singer-songwriter'),
('dance'),
('80s'),
('death metal'),
('Progressive rock'),
('heavy metal'),
('hardcore'),
('british'),
('soul'),
('chillout'),
('electronica'),
('rap'),
('industrial'),
('punk rock'),
('Classical'),
('Soundtrack'),
('blues'),
('thrash metal'),
('90s'),
('metalcore'),
('psychedelic'),
('acoustic'),
('japanese'),
('hip hop'),
('post-rock'),
('Progressive metal'),
('House'),
('german'),
('techno'),
('new wave');
